name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'beta version (e.g. "3.0.0-beta.1")'
        required: true
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  my-testing-second-job:
    runs-on: ubuntu-latest
    steps: 
      - run: "echo second ${{github.event.inputs.version}}"