# This is a basic workflow to help you get started with Actions

name: TESTING_AGAIN

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      myMessage:
        description: 'my message'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Print the message
        run: echo "The message is:${{inputs.myMessage}}"
      - name: nodejsscript
        uses: actions/github-script@v1
        with:
          script: |
            console.log('hello this is jebung');
