name: Manual workflow
# on:
#   workflow_dispatch:
on:
  schedule: 
    - cron: '20 15 * * *'

jobs:
  nodejs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      # or one-off:
      - run: npm install discord.js
      - uses: actions/github-script@v6
        env: 
          nama: ${{ secrets.MY_SECRET }}
          my_var: ${{ vars.MY_VAR }}
          discord_token: ${{ secrets.DISCORD_TOKEN }}
        with:
          script: |
            // Require the necessary discord.js classes
            const { Client, Events, GatewayIntentBits } = require('discord.js');
            const token = process.env.discord_token;

            // Create a new client instance
            const client = new Client({ intents: [GatewayIntentBits.Guilds] });

            // When the client is ready, run this code (only once)
            // We use 'c' for the event parameter to keep it separate from the already defined 'client'
            client.once(Events.ClientReady, async c => {
              console.log(`Ready! Logged in as ${c.user.tag}`);
              client.channels.cache.get("912576389130125396").send("hello world").then(()=>{
                client.destroy();
              })
            });

            // Log in to Discord with your client's token
            client.login(token);
