name: test nodejs

on:
  workflow_dispatch:
    inputs:
      message:
        description: The message to be printed.
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          username: ${{ secrets.GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_PASSWORD }}

      - run: echo "${{ github.event.inputs.message }}" > dummy.txt

      - run: git config --global user.email "kiritosato@gmail.com"

      - run: git config --global user.name "titusefferian"

      - run: git add .

      - run: git commit -m "commit"

      - run: git push origin main
