name: test nodejs

on:
  workflow_dispatch:
    inputs:
      message:
        description: The message to be printed.
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          username: ${{ secrets.GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_PASSWORD }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install @actions/core

      - uses: actions/github-script@v6
        with:
          script: |
            const myCore = require('@actions/core');
            console.log(myCore.getInput('message'));

      - run: git config --global user.email "kiritosato@gmail.com"

      - run: git config --global user.name "titusefferian"

      - run: git add .

      - run: git commit -m "commit"

      - run: git push origin main
