name: test nodejs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: node scripts/my-script.js
      - run: git add .
      - run: git commit -m "commit"
      - run: git push origin main
